// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindProductParams creates a new FindProductParams object
// with the default values initialized.
func NewFindProductParams() *FindProductParams {
	var ()
	return &FindProductParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindProductParamsWithTimeout creates a new FindProductParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindProductParamsWithTimeout(timeout time.Duration) *FindProductParams {
	var ()
	return &FindProductParams{

		timeout: timeout,
	}
}

// NewFindProductParamsWithContext creates a new FindProductParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindProductParamsWithContext(ctx context.Context) *FindProductParams {
	var ()
	return &FindProductParams{

		Context: ctx,
	}
}

// NewFindProductParamsWithHTTPClient creates a new FindProductParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindProductParamsWithHTTPClient(client *http.Client) *FindProductParams {
	var ()
	return &FindProductParams{
		HTTPClient: client,
	}
}

/*FindProductParams contains all the parameters to send to the API endpoint
for the find product operation typically these are written to a http.Request
*/
type FindProductParams struct {

	/*ID
	  The id of the product to retrieve

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find product params
func (o *FindProductParams) WithTimeout(timeout time.Duration) *FindProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find product params
func (o *FindProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find product params
func (o *FindProductParams) WithContext(ctx context.Context) *FindProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find product params
func (o *FindProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find product params
func (o *FindProductParams) WithHTTPClient(client *http.Client) *FindProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find product params
func (o *FindProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find product params
func (o *FindProductParams) WithID(id int64) *FindProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find product params
func (o *FindProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
