// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrGenericError ErrGenericError is a generic error message returned by a server
//
// swagger:model ErrGenericError
type ErrGenericError struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this err generic error
func (m *ErrGenericError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this err generic error based on context it is used
func (m *ErrGenericError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrGenericError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrGenericError) UnmarshalBinary(b []byte) error {
	var res ErrGenericError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
