// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrGenericErrors ErrGenericErrors is a collection of generic or validation errors.
//
// swagger:model ErrGenericErrors
type ErrGenericErrors struct {

	// messages
	Messages []string `json:"messages"`
}

// Validate validates this err generic errors
func (m *ErrGenericErrors) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this err generic errors based on context it is used
func (m *ErrGenericErrors) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrGenericErrors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrGenericErrors) UnmarshalBinary(b []byte) error {
	var res ErrGenericErrors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
